### PR TITLE
Added option to ignore specific error message, fixed JSLint error.

### PR DESCRIPTION
**Pull request by jskungfu**

### CODE REVIEW

**Comment by TimHelck** [comment]
+1

**Comment by vgrinko** [comment]
+1! I think that would really help to my project

**Comment by laurenbrandstein** [comment]
+1

**Comment by jskungfu** [comment]
@yaniswang Did you get chance to review these changes? Let me know if there is anything I can do to improve this feature.

**Comment by Shinigami92** [comment]
We dropped support for `jshint` and will work later on supporting `eslint`
I will close this for now

**Pull request closed without merging**
